### ISSUE TITLE
Alternative to requester pays for AWS sentinel-2 dataset

### ISSUE THREAD

**Issue by bidhya** [sat-utils/sat-search#102]
Browsing through docs and tutorials, it seems downloading Sentinel-2 data requires account on AWS with payment structure setup because the data is in requester pays bucket. Are there alternatives to get sentinel-2 data for free - say for example google cloud. In case of Google, what catalog should I use? I will appreciate any pertinent info with regards to Sentine-2 and sat-search.

**Comment by matthewhanson** [comment]
Hi @bidhya ,

In the latest Earth-search: https://earth-search.aws.element84.com/v0

There are two collections that are in requester pays buckets: `sentinel-s2-l1c` and `sentinel-s2-l2a`. These are indexes of the original JP2K scenes and are located in the eu-central-1 region.

The collection `sentinel-s2-l2a-cogs` is located in us-west-2, is not requester pays, and the data is in Cloud-Optimized GeoTIFF format. So that's the collection you want.

The last released version of sat-search I think points to an older URL, you can install the latest version of sat-search:

$ pip install sat-search==0.3.0-rc1

I'm currently working on getting a final released version this week, might have an rc2 out later today.  In the new version there will not be a default STAC API endpoint, you'll need to provide one at the command line or setting an environment variable.  I'll provide a few endpoint URLs in the README.

**Comment by samsipe** [comment]
@matthewhanson This is great! 

Can you change this to the default collection in the tutorial? I couldn't figure out how to get the .jp2 files to actually download from the requester pays buckets from the tutorial. COGs worked great.
