### ISSUE TITLE
sat-search for Sentinel3A

### ISSUE THREAD

**Issue by nishadhka** [sat-utils/sat-search#112]
There is STAC catalogue for Sentinel 3A in https://meeo-s3-cog.s3.amazonaws.com/catalog.json. However using this with sat-search ends up in error using the code 
```
export STAC_API_URL=https://meeo-s3-cog.s3.amazonaws.com/?t=catalogs
from satsearch import Search
search = Search(bbox=[-110, 39.5, -105, 40.5],datetime='2018-02-12T00:00:00Z/2018-03-18T12:31:12Z')
print('bbox search: %s items' % search.found())
```
```
satsearch.search.SatSearchError: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Method>POST</Method><ResourceType>OBJECT</ResourceType><RequestId>B976E031949FE3D1</RequestId><HostId>xdikqB7hjFVx1nTguC+njOaD0n3q4hqutdppjSVINtWuOfs4p1TkODrS+6YCynAM/3WbI8+IxAQ=</HostId></Error>
```

**Comment by matthewhanson** [comment]
Hi @nishadhka, the issue is that it's just a static catalog of JSON files on s3. They would need to be indexed and an API stood up in order to search them.   [Earth-search](https://element84.com/earth-search/) serves this purpose for AWS Public datasets, but does not include Sentinel-3 currently.  But since there is a static catalog it does make it easier to ingest.  I'll add it to the list of datasets we should ingest into earth-search.

**Comment by nishadhka** [comment]
Hi @matthewhanson, thanks for helping me clarifying the issue. There is similar source which includes data for sentinel-5p as well, https://meeo-s5p.s3.amazonaws.com/index.html?t=catalogs#/?t=catalogs
