### ISSUE TITLE
eo:bands

### ISSUE THREAD

**Issue by jbants** [sat-utils/sat-search#41]
Can you query for `eo:bands` using sat-search?
ref: [stac-spec]( https://github.com/radiantearth/stac-spec/blob/master/extensions/stac-eo-spec.md#itemeobands-field-descriptions)

I'm trying this and can't seem to get anything.

```python
from satsearch.search import Query
search = Query(**{'datetime': '2018-01-01/2018-07-12', 
                  'eo:platform': 'landsat-8',
                  'eo:cloud_cover': '0/50',
                  'eo:bands': {'common_name':'coastal'},
                  'limit':'10',
                  'page':'1'})
```

I've also tried
`'eo:bands': 'b1'`
and 
`'eo:bands': ['B1']`

**Comment by matthewhanson** [comment]
Hi @jbants ,

You can't query for the eo:bands, only things that appear in the "properties" section of the `item` or it's `collection`.  eo:bands, links, and assets are all fields in the top level of the GeoJSON (not in properties) because they are objects rather then primitive data types and can't be searched for.

However, you shouldn't need to search for bands either because every returned scene is going to have the same assets, and you would just refer to the assets URL of the returned scenes.  For instance:

```
scenes = search.scenes()
filenames = scenes.download('B1')
```

This would download the B1 asset for all the scenes returned from the search.

**Comment by jbants** [comment]
Ok, that makes sense. 
I ended up filtering for the bands I need from the assets.

Thanks for the library. Im finding it super useful!

**Comment by matthewhanson** [comment]
Also as an FYI @jbants , since I've still got to do a bunch of documentation, you can refer to assets by key, but also with their common_name as well, so:

```
scene.asset('red')
```

Will return the asset info for the asset that contains a single red band.
