### ISSUE TITLE
Does the sat-search work for Py 27

### ISSUE THREAD

**Issue by pranay-edula** [sat-utils/sat-search#58]
I am trying to use the sat-search functionality on python 2.7. Can you help me out here?

**Comment by dorbodwolf** [comment]
@pranay-edula  did you try the codes in issue 52?

**Comment by pranay-edula** [comment]
@dorbodwolf I tried that and `**{"eo:cloud_cover": "0/30"}` and this part doesn't work on Py27

**Comment by matthewhanson** [comment]
@pranay-edula Thanks for the issue - originally sat-search was supported on Python 2.7, but now it is just tested on Python 3.6. We are currently working on toward the new version of sat-search that will work with the upcoming 0.2.0 release of sat-api, and I'll set up Python 2.7 tests and see where it could be failing. I suspect it won't need much change to make it Python 2.7 compatible.  This should hopefully be out by the end of the year.

**Comment by pranay-edula** [comment]
@matthewhanson Thanks for the update. It would really help if you leave a comment here when you make the changes.

**Comment by dorbodwolf** [comment]
@pranay-edula  you can also build a python 3.6 visualenv to run the codes

**Comment by matthewhanson** [comment]
Hello @pranay-edula ,

Sorry, but sat-search (and it's dependency [sat-stac](https://github.com/sat-utils/sat-stac) are now Python3 only. There were too many Python 3 features that was making it more and more difficult to keep it working in Python 2 without getting hacky.  Since Python 2.7 is going unsupported next year I'd recommend you migrate to Python 3.

Also note there's a new version of sat-search, 0.2.0 which uses the new update of sat-api
