### ISSUE TITLE
Sentinel-2 products are returned when specifically searching for landsat collection

### ISSUE THREAD

**Issue by vka012** [sat-utils/sat-search#65]
Hi

I have updated to the new sat-search 0.2.0 version, and met some problems. I want to specifically search for landsat scenes by specifying a area of intersection, datetime, cloud and cloud cover percentage. My search is:

```
L8results = Search(intersects=footprint,
                   datetime=datetime,
                   property=["eo:cloud_cover<10"],
                   collection='landsat-8-l1'
                   )
```
where datetime is for instance '2018-04-04/2018-05-05', and the footprint is
```
{"coordinates": [[[-5.712890625, 75.95223506623554], [65.7421875, 75.95223506623554], [65.7421875, 82.04574006217713], [-5.712890625, 82.04574006217713], [-5.712890625, 75.95223506623554]]], "type": "Polygon"}
```

The problem is that this search returns both sentinel-2 and landsat-8 products, when I specifically ask for only landsat-8 scenes.
```
print(L8results.found())
238796

print(L8results.items()._collections)
[sentinel-2-l1c, landsat-8-l1]
```

What am I doing wrong?

Best,
Vebjørn

**Comment by matthewhanson** [comment]
Hi @vka012 , the issue is that you need to use the Search.search() when using the alternate querying syntax, so:

```
L8results = Search.search(intersects=footprint,
                   datetime=datetime,
                   property=["eo:cloud_cover<10"],
                   collection='landsat-8-l1'
                   )
```

I didn't want to overload the Search constructor so much it could take any combination of STAC queries, or the alternate syntax so I split it up.

- Search(): use the normal constructor when creating a Search using standard STAC query terms
- Search.search(): use this when creating a Search using the sat-seach alternative query terms.
