### ISSUE TITLE
Catalog change from devseed to element84

### ISSUE THREAD

**Issue by glostis** [sat-utils/sat-search#86]
Hi,

I am working on a project that has CRONed tests that query `sat-search` for Sentinel-2 items over a given AOI and time of interest, always on the same AOI and TOI.
The tests run (roughly) the following code:

```python
list(
    satsearch.Search.search(
        intersects={
            "coordinates": [
                [
                    [31.109125, 29.956381],
                    [31.10827, 30.00148],
                    [31.160085, 30.002214],
                    [31.160916, 29.957114],
                    [31.109125, 29.956381],
                ]
            ],
            "type": "Polygon",
        },
        time="2019-01-15T00:00:00/2019-01-30T00:00:00",
        collection="sentinel-2-l1c",
    ).items()
)
```

Up until September 23rd, 2019, this test gave the expected 3 results, but starting on September 24th, 2019, this query gives 0 results.

After a few investigations, I understood that this was caused by the release of `sat-search==0.2.2`, in which, among other changes, the `sat_search.config.API_URL` variable is changed from https://sat-api.developmentseed.org to https://earth-search.aws.element84.com (see commit https://github.com/sat-utils/sat-search/commit/41df013eaaf42a47c655ad279a23ed7cd481d821).

I guess you intended this change to be transparent for the users, which is why it is not mentioned in the CHANGELOG of the newest release, but it broke our tests.

This issue is to ask about the rationale behind this API switch, and to ask why the `element84` catalog is not as complete as the `devseed` one.

Thanks!

**Comment by matthewhanson** [comment]
Ah sorry about that, it should have been in the CHANGELOG, and also should have been put it in a 0.3 major release rather than a patch increment, after the E84 API was up to date.

At the time the devseed API was having some intermittent problems and I had switched the default API.  You can set the URL by setting the SATUTILS_API_URL environment variable.

The E84 catalog does not have the complete archive for Landsat-8 and Sentinel-2, as there are some additional updates to those catalogs and the code for ingestion to bring them up to date with the latest version of STAC.   Once that is done the E84 API will have all the same records, plus additional collections (CBERS-4, Sentinel-1, NAIP).  I think I jumped the gun on this one, and can release a 0.2.3

**Comment by glostis** [comment]
@matthewhanson thanks for your prompt answer!

I looked a bit too quickly in the code and didn't see the `SATUTILS_API_URL` environment variable which can solve my problem. Thanks!

Do you have any timeline on when the E84 catalog will be fully up to date on Landsat-8 and Sentinel-2?

**Comment by matthewhanson** [comment]
@glostis great.  The goal of sat-search is to be able to point it any STAC API, so the default was really meant to just be set so it would work out of the box for testing it out.   It's really best practice to explicitly set SATUTILS_API_URL to the endpoint you want, but this is not stated anywhere in the README, so I will add that.   Thanks for pointing it out.
